#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "..", "pypkg"))
import ntfy_config

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

server_config = data.get("server_config")
if server_config is not None:
    ntfy_config.write_server_config(server_config)
elif not os.path.exists(ntfy_config.CONFIG_PATH):
    ntfy_config.write_server_config(ntfy_config.default_config(data.get("host", "")))
else:
    ntfy_config.secure_server_config()
