#
# ntfy state/backup include patterns for Restic
# Syntax reference: https://pkg.go.dev/path/filepath#Glob
# Restic --files-from: https://restic.readthedocs.io/en/stable/040_backup.html#including-files
# Only lines starting with "state/" or "volumes/" are considered by NS8.
#

# ntfy databases (users, ACL, tokens, message cache, web push) and attachments
volumes/ntfy-data
# User-managed ntfy configuration
state/config/server.yml
