#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys

import agent

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "pypkg"))
import ntfy_config


if not os.path.exists(ntfy_config.CONFIG_PATH):
    ntfy_config.write_server_config(
        ntfy_config.initial_config(os.getenv("TRAEFIK_HOST", ""))
    )
else:
    ntfy_config.secure_server_config()

for variable in ntfy_config.LEGACY_VARIABLES:
    agent.unset_env(variable)
