#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
config_path = os.path.join("config", "server.yml")
try:
    with open(config_path, "r", encoding="utf-8") as stream:
        config["server_config"] = stream.read()
except FileNotFoundError:
    host = config["host"]
    config["server_config"] = "\n".join((
        f'base-url: "https://{host}"',
        'cache-file: "/var/lib/ntfy/cache.db"',
        'attachment-cache-dir: "/var/lib/ntfy/attachments"',
        'auth-file: "/var/lib/ntfy/auth.db"',
        'auth-default-access: "deny-all"',
        "enable-login: true",
        "enable-signup: false",
        "",
    ))

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
